# personas/tradeops.py
import asyncio

async def on_signal(signal: dict):
    """
    Handles trade signals generated by other personas.
    This persona acts as a risk manager and a gatekeeper for all trades.
    """
    agent = signal.get('agent', 'Unknown')
    instrument = signal.get('instrument', 'N/A')
    
    print(f"[TradeOps] Received SIGNAL from {agent} for {instrument}. Performing pre-trade checks...")
    
    # In a real implementation, this is where you would:
    # 1. Check current exposure for the instrument.
    # 2. Verify available margin in the account.
    # 3. Check against daily loss limits or other risk rules.
    # 4. If any check fails, block the trade.
    # 5. Optionally, require manual approval for large trades.
    
    # For now, we will auto-approve all signals.
    is_approved = True
    
    if is_approved:
        print(f"[TradeOps] Signal from {agent} APPROVED. Forwarding for execution.")
        return True
    else:
        print(f"[TradeOps] Signal from {agent} REJECTED due to risk policy violation.")
        return False
